#!/usr/bin/env php
<?php

if (file_exists(__DIR__.'/../../autoload.php')) {
    require __DIR__.'/../../autoload.php';
} else {
    require __DIR__.'/vendor/autoload.php';
}

$app = new Symfony\Component\Console\Application('PHP-SaaS Cli', '0.6.0');
$app->add(new PHPSaaS\Cli\NewCommand);

$app->run();
